Fix package-lock.json for Ubuntu
- On `npm start`, was getting `Error: Cannot find module '@nrwl/nx-linux-x64-gnu'`
- Deleted `node_modules` and `package-lock.json` and re-ran `npm install`, then was able to `npm start`
- Need to verify on Mac as well